spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/album
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  mvc:
    static-path-pattern: /static/**
  servlet:
    multipart:
      max-file-size: 50Mb
      max-request-size: 50Mb
  thymeleaf:
    cache: false
server:
  tomcat:
    basedir: C:\Users\song\Desktop\upload
